name: Pre Merge Checks

on:
  push:
    branches:
      - "main"      # run on master branch only - no need to start the job automatically otherwise
  pull_request:
    branches:
      - "**"      # run on PRs targeting ANY branch (assuming we check the Gradle wrapper first)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        # We expect our plugin works on all these operating systems
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # Only one JDK is supported
        jdk: [ 17, 21 ]
        example-to-test: [ artifactory-publish, multiple-charts ]
    runs-on: ${{ matrix.os }}
    steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Protect from putting custom jar as a gradle wrapper. Please note - this action validates all such jars
      # https://github.com/gradle/actions/tree/main/wrapper-validation
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      # setup JDK - depending on version selected
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      # Optimize Gradle execution
      # https://github.com/marketplace/actions/build-with-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      # Check each example individually
      - name: Assemble ${{ matrix.example-to-test }}
        # Just run Gradlew here - no need to go deeper as of now
        working-directory: ./${{ matrix.example-to-test }}
        run: ./gradlew helmPackage
